-- DEMO DATA FOR LOCAL DEVELOPMENT ONLY.
-- Every story is illustrative sample content (headlines start with "[Sample]"), not real reporting.
-- Timestamps are relative to "now" so the time tape always has lit slots.
-- Never run this against the production database:  npm run db:init && npm run db:seed
DELETE FROM articles WHERE id LIKE 'sample\_%' ESCAPE '\';
DELETE FROM pipeline_events WHERE article_id LIKE 'sample\_%' ESCAPE '\';

INSERT INTO articles (id, headline, summary, what_happened, why_it_matters, figures_dates, affected_entities, risks_uncertainty,
  category, georgia_related, source_links, trust_score, grammar_checked, fact_checked, status, published_at, created_at, updated_at) VALUES
('sample_01', '[Sample] National Bank of Georgia holds its refinancing rate steady', 'The central bank left its key rate unchanged and said inflation is tracking its target path.', 'The National Bank of Georgia''s Monetary Policy Committee kept the refinancing rate unchanged at its latest meeting. It said annual inflation remains close to target and that domestic demand is growing at a moderate pace.', 'Borrowing costs for Georgian households and businesses stay where they are for now. A steady rate also signals that policymakers see no need to respond to recent exchange-rate moves.', 'Refinancing rate: 8.0%
Inflation: 3.4% year on year
Next meeting: 11 December', 'National Bank of Georgia, Georgian banks, Borrowers', 'The decision depends on the inflation path holding; a sharp lari move or an energy price shock could change the outlook before the next meeting.', 'Economics', 1, '[{"title": "NBG press release: Monetary Policy Committee decision", "url": "https://nbg.gov.ge/en/media/news", "trust_score": 5.0}, {"title": "Georgia''s central bank keeps rate on hold", "url": "https://civil.ge/", "trust_score": 3.5}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes')),
('sample_02', '[Sample] Chipmaker unveils inference accelerator aimed at data centres', 'A new accelerator targets running trained models at lower power per query.', 'The company introduced a new accelerator designed for inference workloads in data centres. It said the part will ship to cloud customers next quarter and is built to cut power use per query compared with its previous generation.', 'Inference is now the largest share of AI computing demand. Lower running costs could change how cloud providers price AI services, and put pressure on rival chip makers.', 'Availability: next quarter
Claimed power saving: 30% per query', 'Cloud providers, Chip makers, AI developers', 'Performance and power figures are company claims and have not been independently benchmarked.', 'AI & Tech', 0, '[{"title": "Newsroom: new inference accelerator", "url": "https://blogs.nvidia.com/", "trust_score": 3.5}, {"title": "The new chip is built for running AI, not training it", "url": "https://www.theverge.com/", "trust_score": 3.5}, {"title": "What the new accelerator means for cloud AI", "url": "https://arstechnica.com/", "trust_score": 3.5}]', 69, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes')),
('sample_03', '[Sample] Spot Bitcoin ETFs log a third straight day of net inflows', 'US-listed Bitcoin funds took in new money for a third consecutive session.', 'US-listed spot Bitcoin exchange-traded funds recorded net inflows for a third consecutive trading day, according to fund-flow data cited by two crypto outlets. Bitcoin traded higher over the same period.', 'Steady ETF inflows are a sign of institutional demand, which has become a main driver of Bitcoin''s price. A reversal would point to cooling appetite.', 'Net inflow, latest day: $412 million
Consecutive inflow days: 3', 'Bitcoin ETF issuers, Crypto exchanges, Investors', 'Daily flow figures are revised as issuers report; single-day data can mislead about the trend.', 'Crypto', 0, '[{"title": "Bitcoin ETFs extend inflow streak", "url": "https://www.coindesk.com/", "trust_score": 3.5}, {"title": "Spot Bitcoin ETFs see third day of inflows", "url": "https://www.theblock.co/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes')),
('sample_04', '[Sample] WTO trims its forecast for global goods trade growth', 'The trade body lowered its outlook, citing weaker demand and higher tariffs.', 'The World Trade Organization cut its forecast for growth in the volume of world merchandise trade, pointing to softer demand in major economies and the effect of higher tariffs. A wire report confirmed the revision.', 'Slower trade growth weighs on exporters and shipping lines, and can feed through to manufacturing output and port volumes.', 'Forecast revision: down 0.6 percentage points
New forecast: 1.9% volume growth', 'Exporters, Shipping lines, Manufacturing', 'Forecasts are sensitive to tariff decisions that are still being negotiated.', 'Global Trade', 0, '[{"title": "WTO: updated trade forecast", "url": "https://www.wto.org/", "trust_score": 5.0}, {"title": "WTO cuts global trade growth forecast", "url": "https://www.reuters.com/", "trust_score": 4.5}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes')),
('sample_05', '[Sample] European climate-tech startup closes a mid-sized Series B', 'A Berlin-based company raised new funding to expand production.', 'A European climate-technology startup announced a Series B round led by an existing investor. It plans to use the money to expand manufacturing and hire engineers, according to two European startup outlets.', 'Funding for climate hardware has been harder to come by than for software. A well-subscribed round suggests investors still back capital-intensive climate companies with a clear route to revenue.', 'Round: Series B
Amount raised: €45 million', 'Startup investors, Climate-tech companies', 'Round size was reported by the outlets from company statements; valuation was not disclosed.', 'VC & Startups', 0, '[{"title": "Climate-tech startup raises Series B", "url": "https://sifted.eu/", "trust_score": 3.5}, {"title": "Berlin startup lands \u20ac45 million", "url": "https://www.eu-startups.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes')),
('sample_06', '[Sample] Mortgage rates ease for a second week', 'Average 30-year mortgage rates edged lower, giving buyers modest relief.', 'Average 30-year fixed mortgage rates edged lower for a second week, according to industry data reported by two property outlets. Applications for purchase loans rose slightly.', 'Even small rate declines widen the pool of buyers who can afford a monthly payment, which can lift sales volumes after a slow period.', '30-year fixed average: 6.42%
Weekly change: down 0.06 points', 'Home buyers, Lenders, Home builders', 'One week of data is not a trend; rates track bond yields, which can reverse quickly.', 'Real Estate', 0, '[{"title": "Mortgage rates slip again", "url": "https://www.bisnow.com/", "trust_score": 3.5}, {"title": "Rates dip for second straight week", "url": "https://www.housingwire.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes')),
('sample_07', '[Sample] Retail brands shift budget from paid search to creator partnerships', 'A survey found a growing share of brands moving spend to creators.', 'A survey of retail marketers found a growing share plan to move budget from paid search towards creator partnerships next year. Two trade publications reported the findings.', 'Search costs have risen, and brands are testing whether creator content delivers cheaper customer acquisition. Agencies and platforms are adjusting their offers.', 'Brands planning to shift spend: 38%
Survey period: third quarter', 'Retail brands, Ad agencies, Creator platforms', 'Survey responses show intent, not actual spend, and the sample skews towards larger brands.', 'Marketing', 0, '[{"title": "Brands move budget to creators", "url": "https://www.adweek.com/", "trust_score": 3.5}, {"title": "Why retailers are cooling on paid search", "url": "https://digiday.com/", "trust_score": 3.5}]', 63, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes')),
('sample_08', '[Sample] Georgia''s annual inflation edges up in the latest reading', 'The statistics office reported a small monthly rise in consumer prices.', 'Georgia''s national statistics office, GeoStat, reported that consumer prices rose slightly over the month, lifting annual inflation by a fraction of a point. Food and transport were the main contributors.', 'Inflation affects the central bank''s rate decisions and household purchasing power. A rise toward the target ceiling would narrow room for rate cuts.', 'Annual inflation: 3.4%
Monthly change: up 0.3%', 'Georgian households, National Bank of Georgia', 'Monthly readings are volatile; the office revises figures when more data arrives.', 'Economics', 1, '[{"title": "GeoStat: consumer price index", "url": "https://www.geostat.ge/en", "trust_score": 5.0}, {"title": "Inflation ticks up in Georgia", "url": "https://civil.ge/", "trust_score": 3.5}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes')),
('sample_09', '[Sample] Research lab releases open weights for a new reasoning model', 'The model and a technical paper were published for researchers to reproduce.', 'A research lab published the weights of a new reasoning model together with a peer-reviewed paper describing its training. Independent outlets confirmed the release and the licence terms.', 'Open weights let universities and smaller companies study and build on the model, and can set a floor for what closed commercial models must offer.', 'Parameters: 70 billion
Licence: permissive, research and commercial use', 'AI researchers, Cloud providers, Start-ups', 'Benchmark claims in the paper have not yet been reproduced by third parties.', 'AI & Tech', 0, '[{"title": "Nature: reasoning model paper", "url": "https://www.nature.com/", "trust_score": 5.0}, {"title": "An open model that reasons", "url": "https://www.technologyreview.com/", "trust_score": 3.5}, {"title": "Lab opens up its newest model", "url": "https://techcrunch.com/", "trust_score": 3.5}]', 100, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes')),
('sample_10', '[Sample] Federal Reserve holds rates and signals a patient approach', 'The Fed kept its policy range unchanged and said it will wait for more data.', 'The Federal Reserve''s policy committee left its target range unchanged and said it will judge future moves on incoming data on inflation and employment. The decision was reported by a wire service and a financial daily.', 'US rates anchor borrowing costs worldwide. A patient Fed supports steady conditions for bond and currency markets, including for emerging markets.', 'Target range: 4.25% to 4.50%
Vote: unanimous', 'US borrowers, Bond markets, Emerging-market currencies', 'The committee noted that the path depends on data; a surprise in inflation or jobs could shift expectations.', 'Economics', 0, '[{"title": "Federal Reserve statement", "url": "https://www.federalreserve.gov/newsevents/pressreleases.htm", "trust_score": 5.0}, {"title": "Fed holds rates, signals patience", "url": "https://www.reuters.com/", "trust_score": 4.5}, {"title": "Fed leaves rates unchanged", "url": "https://www.wsj.com/", "trust_score": 4.0}]', 100, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes')),
('sample_11', '[Sample] Stablecoin issuer publishes its latest reserve attestation', 'The attestation shows reserves above the value of coins in circulation.', 'A major stablecoin issuer published its monthly reserve attestation, which an independent accounting firm prepared. It reports reserves, mostly short-dated government debt, above the value of tokens in circulation.', 'Reserve transparency is central to stablecoin trust and to how regulators treat them.', 'Reserves to liabilities: 102%', 'Stablecoin holders, Exchanges, Regulators', 'An attestation is a snapshot at one date and is not a full audit.', 'Crypto', 0, '[{"title": "Stablecoin reserves exceed liabilities", "url": "https://www.coindesk.com/", "trust_score": 3.5}, {"title": "Issuer posts reserve report", "url": "https://decrypt.co/", "trust_score": 3.5}]', 63, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes')),
('sample_12', '[Sample] Georgia''s finance ministry completes a eurobond placement', 'The government raised funds in international markets at a lower yield than its last issue.', 'The Ministry of Finance of Georgia completed a placement of eurobonds in international markets. A financial news service reported that demand exceeded the amount on offer.', 'A lower borrowing cost reflects investor confidence in Georgia''s credit and reduces future interest bills for the budget.', 'Amount: $500 million
Oversubscription: 3x', 'Government of Georgia, International investors', 'Market conditions can change; the ministry has not published the final allocation table.', 'Economics', 1, '[{"title": "Ministry of Finance announcement", "url": "https://www.mof.ge/en", "trust_score": 5.0}, {"title": "Georgia sells eurobonds at lower yield", "url": "https://www.bloomberg.com/", "trust_score": 4.0}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes')),
('sample_13', '[Sample] Container freight rates drop as capacity returns to key routes', 'Spot rates on major routes fell for the fourth week in a row.', 'Spot container freight rates on the main Asia-Europe and trans-Pacific routes fell for a fourth consecutive week as vessel capacity returned to service. Two shipping publications reported the move.', 'Lower freight costs ease pressure on importers and retailers and can reduce goods inflation with a lag.', 'Index change, week: down 5%', 'Importers, Retailers, Shipping lines', 'Rates can rebound quickly if disruptions return or demand picks up before peak season.', 'Global Trade', 0, '[{"title": "Container rates fall again", "url": "https://theloadstar.com/", "trust_score": 3.5}, {"title": "Spot rates slide on key lanes", "url": "https://www.joc.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes')),
('sample_14', '[Sample] Universities report a rise in applications for data-science degrees', 'Application numbers for data and AI programmes rose year on year.', 'Several universities reported more applications for data-science and AI degrees this year, according to two education publications. Demand is strongest for one-year master''s programmes.', 'Graduate hiring and course supply are adjusting to demand for AI skills, which affects employers'' recruiting plans.', 'Application growth: 21% year on year', 'Universities, Employers, Applicants', 'Application counts do not show how many students enrol or complete.', 'General', 0, '[{"title": "Data-science programmes see surge", "url": "https://www.edsurge.com/", "trust_score": 3.5}, {"title": "AI degrees draw record applicants", "url": "https://www.insidehighered.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'));

INSERT INTO pipeline_events (article_id, stage, outcome, detail, created_at) VALUES
('sample_01', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 4, "supported": 4, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes')),
('sample_02', 'fact_check', 'ok', '{"score": 69, "breakdown": {"credibility": 28.0, "corroboration": 25, "primaryEvidence": 5, "claimSupport": 11.2, "penalties": 0}, "reasons": [], "independentSources": 3, "bestWeight": 3.5, "claims": {"total": 4, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes')),
('sample_03', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes')),
('sample_04', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 5, "supported": 5, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes')),
('sample_05', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes')),
('sample_06', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes')),
('sample_07', 'fact_check', 'ok', '{"score": 63, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 10.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 2, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes')),
('sample_08', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 4, "supported": 4, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes')),
('sample_09', 'fact_check', 'ok', '{"score": 100, "breakdown": {"credibility": 40.0, "corroboration": 25, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 3, "bestWeight": 5.0, "claims": {"total": 5, "supported": 5, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes')),
('sample_10', 'fact_check', 'ok', '{"score": 100, "breakdown": {"credibility": 40.0, "corroboration": 25, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 3, "bestWeight": 5.0, "claims": {"total": 5, "supported": 5, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes')),
('sample_11', 'fact_check', 'ok', '{"score": 63, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 10.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 2, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes')),
('sample_12', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 4, "supported": 4, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes')),
('sample_13', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes')),
('sample_14', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 2, "supported": 2, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'));
