// Turns schema.sql into src/schema.ts so the Worker can create its own tables on first use.
// Runs as part of `npm run build` (and therefore on every Cloudflare build), and a test fails
// if the committed src/schema.ts ever drifts from schema.sql.
import { readFileSync, writeFileSync } from 'node:fs';

const sql = readFileSync(new URL('../schema.sql', import.meta.url), 'utf8');
const statements = sql
  .replace(/--.*$/gm, '') // comments
  .split(';')
  .map((s) => s.replace(/\s+/g, ' ').trim())
  .filter(Boolean);

writeFileSync(
  new URL('../src/schema.ts', import.meta.url),
  `// GENERATED by scripts/gen-schema.mjs from schema.sql. Do not edit by hand.\nexport const SCHEMA_STATEMENTS: string[] = ${JSON.stringify(statements, null, 2)};\n`,
);
console.log(`schema.ts: ${statements.length} statements`);
